import FeaturedProductsSection from '@/components/HomeComponents/heroSections/FeaturedProductsSection'
import HeroSection1 from '@/components/HomeComponents/heroSections/heroSection1'
import ShopbyCategory from '@/components/HomeComponents/heroSections/ShopbyCategory'
import Team from '@/components/HomeComponents/heroSections/Team'
import WhyChoose from '@/components/HomeComponents/heroSections/WhyChoose'
export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
export default function page() {
  return (
    <main>
        <HeroSection1/>
        <FeaturedProductsSection/>
        <ShopbyCategory/>
        <Team/>
        <WhyChoose/>
    </main>
  )
}
